name: CMake

on: 
  workflow_dispatch
  
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: 'Windows Latest x64'
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: apply patch
      run: git apply ../hiredis-win.patch
      working-directory: 3rdparty/qredisclient/3rdparty/hiredis
      
    - name: Setup VS Dev Environment
      # You may pin to the exact commit or the version.
      # uses: seanmiddleditch/gha-setup-vsdevenv@8c6bbf80998779f2bba87b1452832e561b65fd57
      uses: seanmiddleditch/gha-setup-vsdevenv@v3
      
    - name: install zLib
      run: |
        cd 3rdparty
        nuget install zlib-msvc14-x64 -Version 1.2.11.7795
        
    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0
      
    - name: Comfigure with cmake LZ4
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        build-dir: ${{ runner.workspace }}/3rdparty/lz4/build/cmake
        configure-options: -DLZ4_BUNDLED_MODE=ON
        
    - name: Build LZ4
      run: msbuild LZ4.sln /t:Build /p:Configuration=Release
      working-directory: ${{ runner.workspace }}/3rdparty/lz4/build/cmake

    - name: install python requirements
      run: pip3 install -r ${{ runner.workspace }}/src/py/requirements.txt
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.0'
        modules: qtcharts 
        
    - name: Build
      run: |
        qmake ${{ runner.workspace }}/src/rdm.pro
        nmake
